// export const domain = 'http://temp.chitj.com/haoyouhui';
// export const domain = 'http://192.168.1.115/haoyouhui';
// export const domain = 'http://www.haoyouhui2016.com';
// export const domain = 'http://temp.chitj.com/jingjiren';
import { env } from './APP_ROOT_CONFIG';

const domain = env.domain

const ROOT_URL = `${domain}/api/`;
const ROOT_URL2 = `${domain}/app/`;

/*
 *  1.如果你还没有在root_config中加入你的开发者信息，那你需要去添加developer
 *	2.如果你已经添加了developer信息，那么在添加接口的时候需要定义接口的使用者(developer属性名)
 *	3.对应定义你的开发者昵称
 *	例: const girl1 = 'xxx';
*/

const boy1 = 'xuanhe';

export const API_URL = {
	STORELIST : {
		domain : ROOT_URL,
		apiUrl : 'Store/storeList',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Store/storeList',
		remark : '美食列表，包含分页数据结构',
		method : 'GET',
		tableName : 'ez_store',
	},
	STORESCREEN : {
		domain : ROOT_URL,
		apiUrl : 'Store/storeScreen',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Store/storeScreen',
		remark : '列表搜索条件',
		method : 'GET',
		tableName : 'ez_store',
	},
	INDEXINDEXCLASSIFY : {
		domain : ROOT_URL,
		apiUrl : 'Index/indexclassify',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Index/indexclassify',
		remark : '首页分类焦点轮播图',
		method : 'GET',
		tableName : 'ez_store',
	},
	HOTSEARCHKEYWORDSLIST : {
		domain : ROOT_URL,
		apiUrl : 'Goods/hotSearchKeywordsList',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Goods/hotSearchKeywordsList',
		remark : '商品热搜关键词列表',
		method : 'GET',
		tableName : 'ez_store',
	},
	AREAAREALIST : {
		domain : ROOT_URL,
		apiUrl : 'Area/areaList',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Area/areaList',
		remark : '地址选择数据',
		method : 'GET',
		tableName : 'ez_store',
	},
	AREAAREAHOT : {
		domain : ROOT_URL,
		apiUrl : 'Area/areaHot',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Area/areaHot',
		remark : '热门城市数据',
		method : 'GET',
		tableName : 'ez_store',
	},
	SHOPGOODSSEARCH : {
		domain : ROOT_URL,
		apiUrl : 'shopgoods/search',
		author : '韩文博',
		fetchUrl : ROOT_URL+'shopgoods/search',
		remark : '商品根据条件获得列表',
		method : 'GET',
		tableName : 'ez_store',
	},
	SHOPGOODSCATEGORYTREE : {
		domain : ROOT_URL,
		apiUrl : 'shopgoodscategory/tree',
		author : '韩文博',
		fetchUrl : ROOT_URL+'shopgoodscategory/tree',
		remark : '商品分类列表',
		method : 'GET',
		tableName : 'ez_store',
	},
	STOREDETAIL : {
		domain : ROOT_URL,
		apiUrl : 'Store/detail',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Store/detail',
		remark : '店铺详情',
		method : 'GET',
		tableName : 'ez_store',
	},
	SHOPGOODSDETAIL : {
		domain : ROOT_URL,
		apiUrl : 'shopgoods/detail',
		author : '韩文博',
		fetchUrl : ROOT_URL+'shopgoods/detail',
		remark : '单条商品信息',
		method : 'GET',
		tableName : 'ez_store',
	},
	USERSENDREGSMS : {
		domain : ROOT_URL,
		apiUrl : 'user/sendregsms',
		author : '韩文博',
		fetchUrl : ROOT_URL+'user/sendregsms',
		remark : '发送注册校正码',
		method : 'POST',
		tableName : 'ez_store',
		showLoading:true,
	},
	USERLOGIN : {
		domain : ROOT_URL,
		apiUrl : 'User/login',
		author : '韩文博',
		fetchUrl : ROOT_URL+'User/login',
		remark : '登录',
		method : 'POST',
		tableName : 'ez_store',
		showLoading : true,
	},
	USERPASSWORDEDIT : {
		domain : ROOT_URL,
		apiUrl : 'user/passwordedit',
		author : '韩文博',
		fetchUrl : ROOT_URL+'user/passwordedit',
		remark : '修改密码',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	MESSAGESYSTEM : {
		domain : ROOT_URL,
		apiUrl : 'user/sendregsms',
		author : '韩文博',
		fetchUrl : ROOT_URL+'message/system',
		remark : '个人中心的通知',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
	},
	BUYBUYSTEP1 : {
		domain : ROOT_URL,
		apiUrl : 'Buy/buystep1',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Buy/buystep1',
		remark : '生成订单',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
	},
	BUYBUYSTEP2 : {
		domain : ROOT_URL,
		apiUrl : 'Buy/buystep2',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Buy/buystep2',
		remark : '提交订单',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	BUYADDRESSLIST : {
		domain : ROOT_URL,
		apiUrl : 'buy/addresslist',
		author : '韩文博',
		fetchUrl : ROOT_URL+'buy/addresslist',
		remark : '获得收货地址',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
	},
	PAYMENTGETORDERINFO : {
		domain : ROOT_URL,
		apiUrl : 'payment/getorderinfo',
		author : '韩文博',
		fetchUrl : ROOT_URL+'payment/getorderinfo',
		remark : '获得订单信息',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
	},
	PAYMENTTOPAY : {
		domain : ROOT_URL,
		apiUrl : 'payment/topay',
		author : '韩文博',
		fetchUrl : ROOT_URL+'payment/topay',
		remark : '获得支付code',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	STOREGOODSLIST : {
		domain : ROOT_URL,
		apiUrl : 'Store/goodsList',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Store/goodsList',
		remark : '获得各种卷',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
	},
	CARTLISTS : {
		domain : ROOT_URL,
		apiUrl : 'cart/lists',
		author : '韩文博',
		fetchUrl : ROOT_URL+'cart/lists',
		remark : '购物车列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
	},
	CARTADD : {
		domain : ROOT_URL,
		apiUrl : 'Cart/add',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Cart/add',
		remark : '加入购物车',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	SHOPORDERSEARCH : {
		domain : ROOT_URL,
		apiUrl : 'shoporder/search',
		author : '韩文博',
		fetchUrl : ROOT_URL+'shoporder/search',
		remark : '买家的订单列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
	},
	CARTEDIT : {
		domain : ROOT_URL,
		apiUrl : 'cart/edit',
		author : '韩文博',
		fetchUrl : ROOT_URL+'cart/edit',
		remark : '购物车更新商品数量',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
	},
	CARTDEL : {
		domain : ROOT_URL,
		apiUrl : 'cart/del',
		author : '韩文博',
		fetchUrl : ROOT_URL+'cart/del',
		remark : '购物车更新商品数量',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
	},
	STOREGOODSDETAIL : {
		domain : ROOT_URL,
		apiUrl : 'Store/goodsdetail',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Store/goodsdetail',
		remark : '商户团单详情',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
	},
	USERREGISTER : {
		domain : ROOT_URL,
		apiUrl : 'user/register',
		author : '韩文博',
		fetchUrl : ROOT_URL+'user/register',
		remark : '注册',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : true,
	},
	UPLOADIMAGESBINARY : {
		domain : ROOT_URL,
		apiUrl : 'upload/imagesbinary',
		author : '韩文博',
		fetchUrl : ROOT_URL+'upload/imagesbinary',
		remark : '上传图片',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	USERAVATAR : {
		domain : ROOT_URL,
		apiUrl : 'User/avatar',
		author : '韩文博',
		fetchUrl : ROOT_URL+'User/avatar',
		remark : '设置用户头像',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
	},
	STOREORDERCONDITIONWHENCREATEORDER:{
		domain : ROOT_URL,
		apiUrl : 'storeorder/conditionwhencreateorder',
		author : '韩文博',
		fetchUrl : ROOT_URL+'storeorder/conditionwhencreateorder',
		remark : '获得创建订单时所需要的条件',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
	},
	STOREORDERCREATEORDER:{
		domain : ROOT_URL,
		apiUrl : 'storeorder/createorder',
		author : '韩文博',
		fetchUrl : ROOT_URL+'storeorder/createorder',
		remark : '创建订单',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	STOREIMAGESLIST:{
		domain : ROOT_URL,
		apiUrl : 'Store/imageslist',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Store/imageslist',
		remark : '店铺详情内图片列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	STOREORDERSEARCH:{
		domain : ROOT_URL,
		apiUrl : 'storeorder/search',
		author : '韩文博',
		fetchUrl : ROOT_URL+'storeorder/search',
		remark : '买家的订单',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	STOREORDERDETAIL:{
		domain : ROOT_URL,
		apiUrl : 'storeorder/detail',
		author : '韩文博',
		fetchUrl : ROOT_URL+'storeorder/detail',
		remark : '订单详细',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	STOREORDEREVALUATEGOODS:{
		domain : ROOT_URL,
		apiUrl : 'storeorder/evaluategoods',
		author : '韩文博',
		fetchUrl : ROOT_URL+'storeorder/evaluategoods',
		remark : '对某条消费的商品进行评价',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	STOREREFUNDADD:{
		domain : ROOT_URL,
		apiUrl : 'storerefund/add',
		author : '韩文博',
		fetchUrl : ROOT_URL+'storerefund/add',
		remark : '添加订单商品部分退款',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	STOREEVALUATEGOODSEVALUATELIST:{
		domain : ROOT_URL,
		apiUrl : 'storeevaluate/goodsevaluatelist',
		author : '韩文博',
		fetchUrl : ROOT_URL+'storeevaluate/goodsevaluatelist',
		remark : '店铺/店铺下某个商品的评价列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	SHOPORDERDETAIL:{
		domain : ROOT_URL,
		apiUrl : 'shoporder/detail',
		author : '韩文博',
		fetchUrl : ROOT_URL+'shoporder/detail',
		remark : '订单详细',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	ADDRESSDEL:{
		domain : ROOT_URL,
		apiUrl : 'Address/del',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Address/del',
		remark : '买家删除收货地址',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	AREAPROVINCECITYBLOCK:{
		domain : ROOT_URL,
		apiUrl : 'area/provincecityblock',
		author : '韩文博',
		fetchUrl : ROOT_URL+'area/provincecityblock',
		remark : '获得省和市和区县',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	REFUNDINFO:{
		domain : ROOT_URL,
		apiUrl : 'refund/info',
		author : '韩文博',
		fetchUrl : ROOT_URL+'refund/info',
		remark : '获得要退款的订单信息商品信息',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	REFUNDADDREFUNDALL:{
		domain : ROOT_URL,
		apiUrl : 'refund/addrefundall',
		author : '韩文博',
		fetchUrl : ROOT_URL+'refund/addrefundall',
		remark : '添加订单为全部退款即取消订单',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	REFUNDADD:{
		domain : ROOT_URL,
		apiUrl : 'refund/add',
		author : '韩文博',
		fetchUrl : ROOT_URL+'refund/add',
		remark : '添加订单商品部分退款',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	REFUNDSEARCH:{
		domain : ROOT_URL,
		apiUrl : 'refund/search',
		author : '韩文博',
		fetchUrl : ROOT_URL+'refund/search',
		remark : '退款列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	RETURNSEARCH:{
		domain : ROOT_URL,
		apiUrl : 'return/search',
		author : '韩文博',
		fetchUrl : ROOT_URL+'return/search',
		remark : '退货列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	REFUNDDETAIL:{
		domain : ROOT_URL,
		apiUrl : 'refund/detail',
		author : '韩文博',
		fetchUrl : ROOT_URL+'refund/detail',
		remark : '退款记录查看',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	RETURNDELAY:{
		domain : ROOT_URL,
		apiUrl : 'return/delay',
		author : '韩文博',
		fetchUrl : ROOT_URL+'return/delay',
		remark : '修改退货记录的延迟时间',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	RETURNSHIPINFO:{
		domain : ROOT_URL,
		apiUrl : 'return/shipinfo',
		author : '韩文博',
		fetchUrl : ROOT_URL+'return/shipinfo',
		remark : '发货时所需要的退货信息及物流信息',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	RETURNSHIP:{
		domain : ROOT_URL,
		apiUrl : 'return/ship',
		author : '韩文博',
		fetchUrl : ROOT_URL+'return/ship',
		remark : '修改退货记录为发货',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	USERSENDFINDPASSWORDSMS:{
		domain : ROOT_URL,
		apiUrl : 'user/sendfindpasswordsms',
		author : '韩文博',
		fetchUrl : ROOT_URL+'user/sendfindpasswordsms',
		remark : '发送找回密码校正码',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : true,
	},
	USERFINDPASSWORD:{
		domain : ROOT_URL,
		apiUrl : 'user/findpassword',
		author : '韩文博',
		fetchUrl : ROOT_URL+'user/findpassword',
		remark : '找回密码',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : true,
	},
	INDEXAPPLATESTVERSION:{
		domain : ROOT_URL,
		apiUrl : 'index/applatestversion',
		author : '韩文博',
		fetchUrl : ROOT_URL+'index/applatestversion',
		remark : '获得APP最新版本',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	INDEXCAROUSELWELCOME:{
		domain : ROOT_URL,
		apiUrl : 'index/carouselwelcome',
		author : '韩文博',
		fetchUrl : ROOT_URL+'index/carouselwelcome',
		remark : '欢迎页轮播图',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	INDEXAPPUPDATE:{
		domain : ROOT_URL,
		apiUrl : 'index/appupdate',
		author : '韩文博',
		fetchUrl : ROOT_URL+'index/appupdate',
		remark : 'app更新检查',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	USERGETUSERINFO : {
		domain : ROOT_URL,
		apiUrl : 'User/getUserInfo',
		author : '韩文博',
		fetchUrl : ROOT_URL+'User/getUserInfo',
		remark : '获取用户信息',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	USERPOINTSUSERPOINTSLOGLIST : {
		domain : ROOT_URL,
		apiUrl : 'userpoints/userpointsloglist',
		author : '韩文博',
		fetchUrl : ROOT_URL+'userpoints/userpointsloglist',
		remark : '积分账单',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	USERCOLLECTEDSHOPGOODS : {
		domain : ROOT_URL,
		apiUrl : 'User/collectedGoods',
		author : '韩文博',
		fetchUrl : ROOT_URL+'User/collectedGoods',
		remark : '用户收藏过的商品列表',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : false,
	},
	COLLECTISDONE : {
		domain : ROOT_URL,
		apiUrl : 'Collect/isDone',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Collect/isDone',
		remark : '判断某条是否已经收藏',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	COLLECTDEL : {
		domain : ROOT_URL,
		apiUrl : 'Collect/del',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Collect/del',
		remark : '取消收藏',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	COLLECTADD : {
		domain : ROOT_URL,
		apiUrl : 'Collect/add',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Collect/add',
		remark : '收藏',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	SHAREADD : {
		domain : ROOT_URL,
		apiUrl : 'share/add',
		author : '韩文博',
		fetchUrl : ROOT_URL+'share/add',
		remark : '收藏',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	TOPICLISTS : {
		domain : ROOT_URL,
		apiUrl : 'topic/lists',
		author : '韩文博',
		fetchUrl : ROOT_URL+'topic/lists',
		remark : '获得某个专题分类下的专题列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	PREDEPOSITPDCASHADD : {
		domain : ROOT_URL,
		apiUrl : 'predeposit/pdcashadd',
		author : '韩文博',
		fetchUrl : ROOT_URL+'predeposit/pdcashadd',
		remark : '申请提现',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	PREDEPOSITPDCASHLIST : {
		domain : ROOT_URL,
		apiUrl : 'predeposit/pdcashlist',
		author : '韩文博',
		fetchUrl : ROOT_URL+'predeposit/pdcashlist',
		remark : '申请明细列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	STOREINDEXBOMBSTORE : {
		domain : ROOT_URL,
		apiUrl : 'store/indexbombstore',
		author : '韩文博',
		fetchUrl : ROOT_URL+'store/indexbombstore',
		remark : '首页的推荐爆店活动',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	SHOPGOODSEVALUATELIST : {
		domain : ROOT_URL,
		apiUrl : 'shopgoods/evaluatelist',
		author : '韩文博',
		fetchUrl : ROOT_URL+'shopgoods/evaluatelist',
		remark : '某条商品的评价信息',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	USEREDITPROFILE : {
		domain : ROOT_URL,
		apiUrl : 'user/editProfile',
		author : '韩文博',
		fetchUrl : ROOT_URL+'user/editProfile',
		remark : '修改资料',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	CROWDFUNDINGPROJECTPROJECTSCREEN : {
		domain : ROOT_URL,
		apiUrl : 'Crowdfundingproject/projectscreen',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Crowdfundingproject/projectscreen',
		remark : '众筹搜索条件',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	CROWDFUNDINGPROJECTPROJECTLIST : {
		domain : ROOT_URL,
		apiUrl : 'Crowdfundingproject/projectlist',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Crowdfundingproject/projectlist',
		remark : '众筹列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	CROWDFUNDINGPROJECTPROJECTDETAIL : {
		domain : ROOT_URL,
		apiUrl : 'Crowdfundingproject/projectdetail',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Crowdfundingproject/projectdetail',
		remark : '众筹项目详情',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	CROWDFUNDINGPROJECTPROJECTDYNAMIC : {
		domain : ROOT_URL,
		apiUrl : 'Crowdfundingproject/projectdynamic',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Crowdfundingproject/projectdynamic',
		remark : '项目动态列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	CROWDFUNDINGPROJECTPAYPROJECTBUY : {
		domain : ROOT_URL,
		apiUrl : 'Crowdfundingprojectpay/projectbuy',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Crowdfundingprojectpay/projectbuy',
		remark : '众筹购买',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	CROWDFUNDINGPROJECTORDERINDEX : {
		domain : ROOT_URL,
		apiUrl : 'Crowdfundingprojectorder/index',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Crowdfundingprojectorder/index',
		remark : '用户众筹订单列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	CROWDFUNDINGPROJECTORDERORDERDETAIL : {
		domain : ROOT_URL,
		apiUrl : 'Crowdfundingprojectorder/orderdetail',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Crowdfundingprojectorder/orderdetail',
		remark : '众筹项目订单详情',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	PROCUREMENTDEMANDINDEX : {
		domain : ROOT_URL,
		apiUrl : 'Procurementdemand/index',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Procurementdemand/index',
		remark : '集团采购列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	SUPPLYINFORMATIONSUPPLIERLIST : {
		domain : ROOT_URL,
		apiUrl : 'Supplyinformation/supplierlist',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Supplyinformation/supplierlist',
		remark : '供货信息列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	PAYMENTPAYMENTLIST : {
		domain : ROOT_URL,
		apiUrl : 'Payment/paymentList',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Payment/paymentList',
		remark : '支付方式列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	BRANDALLIANCEINDEX : {
		domain : ROOT_URL,
		apiUrl : 'Brandalliance/index',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Brandalliance/index',
		remark : '加盟品牌列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	BRANDALLIANCEBRANDCLASSIFY : {
		domain : ROOT_URL,
		apiUrl : 'Brandalliance/brandclassify',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Brandalliance/brandclassify',
		remark : '加盟品牌列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	BRANDALLIANCEDETAIL : {
		domain : ROOT_URL,
		apiUrl : 'Brandalliance/detail',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Brandalliance/detail',
		remark : '加盟品牌详情',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	MESSAGESYSTEMUNREAD:{
		domain : ROOT_URL,
		apiUrl : 'Message/systemUnread',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Message/systemUnread',
		remark : '统计系统站内信未读条数',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	NEWSTODAYROW:{
		domain : ROOT_URL,
		apiUrl : 'news/todayRow',
		author : '韩文博',
		fetchUrl : ROOT_URL+'news/todayRow',
		remark : '今日头条',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	NEWSDETAILCONTENT:{
		domain : ROOT_URL2,
		apiUrl : 'news/detailcontent',
		author : '韩文博',
		fetchUrl : ROOT_URL2+'news/detailcontent',
		remark : '今日头条webview',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	EVALUATETOSHOP:{
		domain : ROOT_URL,
		apiUrl : 'evaluate/toshop',
		author : '韩文博',
		fetchUrl : ROOT_URL+'evaluate/toshop',
		remark : '对店铺进行评价',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	USERMYREFEREE:{
		domain : ROOT_URL,
		apiUrl : 'User/myreferee',
		author : '孙泉',
		fetchUrl : ROOT_URL+'User/myreferee',
		remark : '我的邀请人',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	USERQUERYMYREFEREE:{
		domain : ROOT_URL,
		apiUrl : 'User/queryMyreferee',
		author : '孙泉',
		fetchUrl : ROOT_URL+'User/queryMyreferee',
		remark : '查询邀请人',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	BIGSHOTBIGSHOTLIST:{
		domain : ROOT_URL,
		apiUrl : 'BigShot/bigshotlist',
		author : '孙泉',
		fetchUrl : ROOT_URL+'BigShot/bigshotlist',
		remark : '大咖空间',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	USERADDMYREFEREE:{
		domain : ROOT_URL,
		apiUrl : 'User/addMyReferee',
		author : '孙泉',
		fetchUrl : ROOT_URL+'User/addMyReferee',
		remark : '添加我填写的推荐人的码',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	SHOPGOODSCATEGORYSON:{
		domain : ROOT_URL,
		apiUrl : 'shopgoodscategory/son',
		author : '韩文博',
		fetchUrl : ROOT_URL+'shopgoodscategory/son',
		remark : '获得某一个分类下的子分类（商品分类隐藏属性）',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	ADRECOMMENDSEARCH:{
		domain : ROOT_URL,
		apiUrl : 'adrecommend/search',
		author : '韩文博',
		fetchUrl : ROOT_URL+'adrecommend/search',
		remark : '各种首页推荐位置',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	SHOPGOODSPORTALPRESALELIST:{
		domain : ROOT_URL,
		apiUrl : 'shopgoods/portalPreSaleList',
		author : '韩文博',
		fetchUrl : ROOT_URL+'shopgoods/portalPreSaleList',
		remark : '临时预售',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	SHOPGOODSPRESALECATEGORYGOODSLIST:{
		domain : ROOT_URL,
		apiUrl : 'shopgoods/preSaleCategoryGoodsList',
		author : '韩文博',
		fetchUrl : ROOT_URL+'shopgoods/preSaleCategoryGoodsList',
		remark : '预售列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	TALENTSHOWINDEX:{
		domain : ROOT_URL,
		apiUrl : 'talentshow/index',
		author : '韩文博',
		fetchUrl : ROOT_URL+'talentshow/index',
		remark : '达人秀列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	TALENTSHOWDETAIL:{
		domain : ROOT_URL,
		apiUrl : 'talentshow/detail',
		author : '韩文博',
		fetchUrl : ROOT_URL+'talentshow/detail',
		remark : '达人秀详情',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	TALENTSHOWSEARCH:{
		domain : ROOT_URL,
		apiUrl : 'talentshow/search',
		author : '韩文博',
		fetchUrl : ROOT_URL+'talentshow/search',
		remark : '达人秀查询',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	AREALISTS:{
		domain : ROOT_URL,
		apiUrl : 'area/lists',
		author : '韩文博',
		fetchUrl : ROOT_URL+'area/lists',
		remark : '省份查询',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	TALENTSHOWCATEGORYSON:{
		domain : ROOT_URL,
		apiUrl : 'talentshowcategory/son',
		author : '韩文博',
		fetchUrl : ROOT_URL+'talentshowcategory/son',
		remark : '达人秀分类',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	CUSTOMIZEDCATEGORYTREE:{
		domain : ROOT_URL,
		apiUrl : 'customizedcategory/tree',
		author : '韩文博',
		fetchUrl : ROOT_URL+'customizedcategory/tree',
		remark : '定制分类',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	CUSTOMIZEDSEARCH:{
		domain : ROOT_URL,
		apiUrl : 'customized/search',
		author : '韩文博',
		fetchUrl : ROOT_URL+'customized/search',
		remark : '定制搜索',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	CUSTOMIZEDRECOMMEND:{
		domain : ROOT_URL,
		apiUrl : 'customized/recommend',
		author : '韩文博',
		fetchUrl : ROOT_URL+'customized/recommend',
		remark : '定制推荐厂商',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	CUSTOMIZEDDETAIL:{
		domain : ROOT_URL,
		apiUrl : 'customized/detail',
		author : '韩文博',
		fetchUrl : ROOT_URL+'customized/detail',
		remark : '定制详情',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	CASTINGCATEGORYSON:{
		domain : ROOT_URL,
		apiUrl : 'castingcategory/son',
		author : '韩文博',
		fetchUrl : ROOT_URL+'castingcategory/son',
		remark : '大咖分类',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	CASTINGSEARCH:{
		domain : ROOT_URL,
		apiUrl : 'casting/search',
		author : '韩文博',
		fetchUrl : ROOT_URL+'casting/search',
		remark : '大咖搜索',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	CASTINGDETAIL:{
		domain : ROOT_URL,
		apiUrl : 'casting/detail',
		author : '韩文博',
		fetchUrl : ROOT_URL+'casting/detail',
		remark : '大咖详情',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	STORENEARESTOPERATIONCENTERSTORE:{
		domain : ROOT_URL,
		apiUrl : 'store/nearestoperationcenterstore',
		author : '韩文博',
		fetchUrl : ROOT_URL+'store/nearestoperationcenterstore',
		remark : '最近运营中心店铺',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	STOREOPERATIONCENTERSTORELIST:{
		domain : ROOT_URL,
		apiUrl : 'store/operationcenterstorelist',
		author : '韩文博',
		fetchUrl : ROOT_URL+'store/operationcenterstorelist',
		remark : '最近运营中心店铺列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	INFOSEARCH:{
		domain : ROOT_URL,
		apiUrl : 'Info/search',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Info/search',
		remark : '定制中的一些新闻',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	SHOPORDERCHANGESTATE : {
		domain : ROOT_URL,
		apiUrl : 'shoporder/changestate',
		author : '韩文博',
		fetchUrl : ROOT_URL+'shoporder/changestate',
		remark : '确认收货',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	EVALUATETOGOODS : {
		domain : ROOT_URL,
		apiUrl : 'evaluate/togoods',
		author : '韩文博',
		fetchUrl : ROOT_URL+'evaluate/togoods',
		remark : '对单商品进行评价',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : true,
	},
	CROWDFUNDINGPROJECTORDERCHANGESTATE : {
		domain : ROOT_URL,
		apiUrl : 'Crowdfundingprojectorder/changeState',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Crowdfundingprojectorder/changeState',
		remark : '众筹确认收货',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : false,
	},
	USEROPENLOGIN : {
		domain : ROOT_URL,
		apiUrl : 'user/openlogin',
		author : '韩文博',
		fetchUrl : ROOT_URL+'user/openlogin',
		remark : '第三方登陆',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : true,
	},
	USERACCOUNTBINDOPENUSER : {
		domain : ROOT_URL,
		apiUrl : 'user/accountbindopenuser',
		author : '韩文博',
		fetchUrl : ROOT_URL+'user/accountbindopenuser',
		remark : '账号绑定第三方用户',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : true,
	},
	USEROPENUSERBINDPHONE : {
		domain : ROOT_URL,
		apiUrl : 'user/openuserbindphone',
		author : '韩文博',
		fetchUrl : ROOT_URL+'user/openuserbindphone',
		remark : '当前用户绑定手机号',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : true,
	},
	USERSENDREPLACEOLDPHONESMS : {
		domain : ROOT_URL,
		apiUrl : 'User/sendReplaceOldPhoneSms',
		author : '孙泉',
		fetchUrl : ROOT_URL+'User/sendReplaceOldPhoneSms',
		remark : '发送更换手机号原手机号校正码',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : true,
	},
	USERSENDREPLACNEWPHONESMS : {
		domain : ROOT_URL,
		apiUrl : 'User/sendReplacNewPhoneSms',
		author : '孙泉',
		fetchUrl : ROOT_URL+'User/sendReplacNewPhoneSms',
		remark : '发送更换手机号新手机号校正码',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : true,
	},
	USERCHANGEPHONE : {
		domain : ROOT_URL,
		apiUrl : 'User/changePhone',
		author : '孙泉',
		fetchUrl : ROOT_URL+'User/changePhone',
		remark : '更换手机号',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : true,
	},
	SHOPGOODSCCYPGOODSLIST : {
		domain : ROOT_URL,
		apiUrl : 'shopgoods/ccypGoodsList',
		author : '韩文博',
		fetchUrl : ROOT_URL+'shopgoods/ccypGoodsList',
		remark : '村村优品的全部和点击分类的商品列表',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
	},
	SHOPGOODSCATEGORYCUSTOMTREE : {
		domain : ROOT_URL,
		apiUrl : 'shopgoodscategory/customtree',
		author : '韩文博',
		fetchUrl : ROOT_URL+'shopgoodscategory/customtree',
		remark : '过滤过的商城分类',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
	},
	ADRECOMMENDCCYPADRECOMMENDCATEGORYLIST : {
		domain : ROOT_URL,
		apiUrl : 'adrecommend/ccypadrecommendcategorylist',
		author : '韩文博',
		fetchUrl : ROOT_URL+'adrecommend/ccypadrecommendcategorylist',
		remark : '村村优品首页推荐的分类列表',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
	},
	SHOPGOODSSEARCHBYADRECOMMEND : {
		domain : ROOT_URL,
		apiUrl : 'shopgoods/searchbyadrecommend',
		author : '韩文博',
		fetchUrl : ROOT_URL+'shopgoods/searchbyadrecommend',
		remark : '根据推荐条件进行搜索商品列表',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
	},
	SHOPGOODSVISITEDRECORD : {
		domain : ROOT_URL,
		apiUrl : 'shopgoods/visitedrecord',
		author : '韩文博',
		fetchUrl : ROOT_URL+'shopgoods/visitedrecord',
		remark : '为您推荐的接口',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
	},
	BUILDINGINDEX : {
		domain : ROOT_URL,
		apiUrl : 'Building/index',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Building/index',
		remark : '楼盘列表',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	BUILDINGDETAIL : {
		domain : ROOT_URL,
		apiUrl : 'Building/detail',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Building/detail',
		remark : '楼盘详情',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	BUILDINGLAYOUTDETAIL : {
		domain : ROOT_URL,
		apiUrl : 'Building/layoutdetail',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Building/layoutdetail',
		remark : '户型详情',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	BUILDINGDYNAMICINDEX : {
		domain : ROOT_URL,
		apiUrl : 'Buildingdynamic/index',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Buildingdynamic/index',
		remark : '最新动态列表',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	BUILDINGDYNAMICLIKEDYNAMIC : {
		domain : ROOT_URL,
		apiUrl : 'Buildingdynamic/likedynamic',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Buildingdynamic/likedynamic',
		remark : '楼盘动态点赞',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : true,
		developer : boy1,
	},
	BUILDINGDYNAMICCANCELLIKE : {
		domain : ROOT_URL,
		apiUrl : 'Buildingdynamic/cancellike',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Buildingdynamic/cancellike',
		remark : '楼盘动态取消点赞',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : true,
		developer : boy1,
	},
	BUILDINGDYNAMICADDCOMMENT : {
		domain : ROOT_URL,
		apiUrl : 'Buildingdynamic/addcomment',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Buildingdynamic/addcomment',
		remark : '楼盘动态添加评论',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : true,
		developer : boy1,
	},
	BUILDINGDYNAMICDELCOMMENT : {
		domain : ROOT_URL,
		apiUrl : 'Buildingdynamic/delcomment',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Buildingdynamic/delcomment',
		remark : '楼盘动态删除评论',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : true,
		developer : boy1,
	},
	BUILDINGCOLLECT : {
		domain : ROOT_URL,
		apiUrl : 'Building/collect',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Building/collect',
		remark : '楼盘收藏',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : true,
		developer : boy1,
	},
	BUILDINGCANCELCOLLECT : {
		domain : ROOT_URL,
		apiUrl : 'Building/cancelcollect',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Building/cancelcollect',
		remark : '楼盘取消收藏',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : true,
		developer : boy1,
	},
	ADVLISTS:{
		domain : ROOT_URL,
		apiUrl : 'Adv/lists',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Adv/lists',
		remark : '首页焦点图',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	BUILDINGCATEGORYINDEX:{
		domain : ROOT_URL,
		apiUrl : 'Buildingcategory/index',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Buildingcategory/index',
		remark : '楼盘列表筛选条件',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	BUILDINGSEARCH:{
		domain : ROOT_URL,
		apiUrl : 'Building/search',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Building/search',
		remark : '楼盘顶部搜索栏',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	BUILDINGDYNAMICNEWESTDYNAMIC:{
		domain : ROOT_URL,
		apiUrl : 'Buildingdynamic/newestdynamic',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Buildingdynamic/newestdynamic',
		remark : '最新动态列表',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	BUILDINGREPORTCUSTOMERCUSTOMER:{
		domain : ROOT_URL,
		apiUrl : 'Buildingreportcustomer/customer',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Buildingreportcustomer/customer',
		remark : '客户首页',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	BROKERSHOPINDEX:{
		domain : ROOT_URL,
		apiUrl : 'Brokershop/index',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Brokershop/index',
		remark : '我的店铺',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	BROKERSHOPBUILDINGLIST:{
		domain : ROOT_URL,
		apiUrl : 'Brokershop/buildinglist',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Brokershop/buildinglist',
		remark : '我的店铺',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	BROKERSHOPADD:{
		domain : ROOT_URL,
		apiUrl : 'Brokershop/add',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Brokershop/add',
		remark : '我的店铺里添加楼盘',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : true,
		developer : boy1,
	},
	BUILDINGBROKERBUILDING:{
		domain : ROOT_URL,
		apiUrl : 'building/brokerbuilding',
		author : '孙泉',
		fetchUrl : ROOT_URL+'building/brokerbuilding',
		remark : '我的楼盘',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	BROKERSHOPDEL:{
		domain : ROOT_URL,
		apiUrl : 'Brokershop/del',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Brokershop/del',
		remark : '我的店铺里 删除楼盘',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	BROKERSHOPSORT:{
		domain : ROOT_URL,
		apiUrl : 'Brokershop/sort',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Brokershop/sort',
		remark : '我的店铺排序',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	BUILDINGREPORTCUSTOMERCHOICEBUILDING:{
		domain : ROOT_URL,
		apiUrl : 'Buildingreportcustomer/choicebuilding',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Buildingreportcustomer/choicebuilding',
		remark : '报备楼盘列表',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	BUILDINGREPORTADDREPORT:{
		domain : ROOT_URL,
		apiUrl : 'Buildingreport/addreport',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Buildingreport/addreport',
		remark : '报备',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : true,
		developer : boy1,
	},
	BUILDINGREPORTINDEX:{
		domain : ROOT_URL,
		apiUrl : 'Buildingreport/index',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Buildingreport/index',
		remark : '报备记录列表',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : false,
		developer : boy1,
	},
	BUILDINGREPORTDETAIL:{
		domain : ROOT_URL,
		apiUrl : 'Buildingreport/detail',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Buildingreport/detail',
		remark : '报备详情',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : false,
		developer : boy1,
	},
	BUILDINGREPORTCUSTOMERSEARCH:{
		domain : ROOT_URL,
		apiUrl : 'Buildingreportcustomer/search',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Buildingreportcustomer/search',
		remark : '客户列表',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	BUILDINGREPORTCUSTOMERCUSTOMERDETAIL:{
		domain : ROOT_URL,
		apiUrl : 'Buildingreportcustomer/customerdetail',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Buildingreportcustomer/customerdetail',
		remark : '客户详情',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	BUILDINGREPORTCUSTOMEREDITINTENTION:{
		domain : ROOT_URL,
		apiUrl : 'Buildingreportcustomer/editintention',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Buildingreportcustomer/editintention',
		remark : '修改客户购房意向',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : true,
		developer : boy1,
	},
	BUILDINGREPORTCUSTOMERADDREPORTBUILDING:{
		domain : ROOT_URL,
		apiUrl : 'Buildingreportcustomer/addreportbuilding',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Buildingreportcustomer/addreportbuilding',
		remark : '添加报备楼盘',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : true,
		developer : boy1,
	},
	BUILDINGREPORTCUSTOMERADD:{
		domain : ROOT_URL,
		apiUrl : 'Buildingreportcustomer/add',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Buildingreportcustomer/add',
		remark : '添加客户',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : true,
		developer : boy1,
	},
	BUILDINGREPORTCUSTOMEREDIT:{
		domain : ROOT_URL,
		apiUrl : 'Buildingreportcustomer/edit',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Buildingreportcustomer/edit',
		remark : '编辑客户',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : true,
		developer : boy1,
	},
	BUILDINGREPORTCUSTOMERDEL:{
		domain : ROOT_URL,
		apiUrl : 'Buildingreportcustomer/del',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Buildingreportcustomer/del',
		remark : '删除客户',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : true,
		developer : boy1,
	},
	CUSTOMERFOLLOWLOGADD:{
		domain : ROOT_URL,
		apiUrl : 'Customerfollowlog/add',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Customerfollowlog/add',
		remark : '添加客户跟进日志',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : true,
		developer : boy1,
	},
	CUSTOMERFOLLOWLOGINDEX:{
		domain : ROOT_URL,
		apiUrl : 'Customerfollowlog/index',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Customerfollowlog/index',
		remark : '客户跟进日志列表',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	GOODSSEARCH:{
		domain : ROOT_URL,
		apiUrl : 'Goods/search',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Goods/search',
		remark : '商品列表',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	GOODSCATEGORYSON:{
		domain : ROOT_URL,
		apiUrl : 'Goodscategory/son',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Goodscategory/son',
		remark : '商品分类',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	GOODSDETAIL:{
		domain : ROOT_URL,
		apiUrl : 'Goods/detail',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Goods/detail',
		remark : '商品详情',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	GOODSEVALUATELIST:{
		domain : ROOT_URL,
		apiUrl : 'Goods/evaluatelist',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Goods/evaluatelist',
		remark : '某条商品的评价信息',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	ADRECOMMENDLISTS:{
		domain : ROOT_URL,
		apiUrl : 'AdRecommend/lists',
		author : '韩文博',
		fetchUrl : ROOT_URL+'AdRecommend/lists',
		remark : '推荐列表',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : false,
		showLoading : false,
		developer : boy1,
	},
	ADDRESSDETAIL : {
		domain : ROOT_URL,
		apiUrl : 'Address/detail',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Address/detail',
		remark : '获取收货地址信息',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : false,
	},
	ADDRESSLISTS:{
		domain : ROOT_URL,
		apiUrl : 'Address/lists',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Address/lists',
		remark : '买家收货地址列表',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : false,
		developer : boy1,
	},
	ADDRESSSETDEFAULT:{
		domain : ROOT_URL,
		apiUrl : 'Address/setDefault',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Address/setDefault',
		remark : '买家设置默认收货地址',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : true,
		developer : boy1,
	},
	ADDRESSEDIT:{
		domain : ROOT_URL,
		apiUrl : 'Address/edit',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Address/edit',
		remark : '买家修改收货地址',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : true,
		developer : boy1,
	},
	ADDRESSADD:{
		domain : ROOT_URL,
		apiUrl : 'Address/add',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Address/add',
		remark : '添加新的收货地址',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : true,
		developer : boy1,
	},
	ADDRESSGETDEFAULT:{
		domain : ROOT_URL,
		apiUrl : 'Address/getDefault',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Address/getDefault',
		remark : '获得默认收货地址',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : false,
		developer : boy1,
	},
	BUYPAY:{
		domain : ROOT_URL,
		apiUrl : 'Buy/pay',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Buy/pay',
		remark : '收银台',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : false,
		developer : boy1,
	},
	ORDERSEARCH:{
		domain : ROOT_URL,
		apiUrl : 'Order/search',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Order/search',
		remark : '订单列表',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : false,
		developer : boy1,
	},
	VOUCHERUSERVOUCHERLIST:{
		domain : ROOT_URL,
		apiUrl : 'voucher/userVoucherList',
		author : '韩文博',
		fetchUrl : ROOT_URL+'voucher/userVoucherList',
		remark : '我的优惠券',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : false,
		developer : boy1,
	},
	ORDERDETAIL:{
		domain : ROOT_URL,
		apiUrl : 'Order/detail',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Order/detail',
		remark : '订单详情',
		method : 'GET',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : false,
		developer : boy1,
	},
	ORDERCHANGESTATE:{
		domain : ROOT_URL,
		apiUrl : 'Order/changeState',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Order/changeState',
		remark : '修改订单状态',
		method : 'POST',
		tableName : 'xxxx',
		needLogin : true,
		showLoading : true,
		developer : boy1,
	},
	GOODSEVALUATEADDEVALUATEIMAGE : {
		domain : ROOT_URL,
		apiUrl : 'Goodsevaluate/addEvaluateImage',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Goodsevaluate/addEvaluateImage',
		remark : '上传图片',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : true,
	},
	GOODSEVALUATETOORDERANDORDERGOODS : {
		domain : ROOT_URL,
		apiUrl : 'Goodsevaluate/toOrderAndOrderGoods',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Goodsevaluate/toOrderAndOrderGoods',
		remark : '对订单和订单商品进行整体评价',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	GOODSHOTSEARCHKEYWORDSLIST : {
		domain : ROOT_URL,
		apiUrl : 'Goods/hotSearchKeywordsList',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Goods/hotSearchKeywordsList',
		remark : '对订单和订单商品进行整体评价',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	EVALUATEMYGOODS : {
		domain : ROOT_URL,
		apiUrl : 'Evaluate/mygoods',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Evaluate/mygoods',
		remark : '我的商品的评价列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	USERHELPTYPELIST : {
		domain : ROOT_URL,
		apiUrl : 'Userhelp/typelist',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Userhelp/typelist',
		remark : '意见反馈选项',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	USERHELPADDADVICE : {
		domain : ROOT_URL,
		apiUrl : 'Userhelp/addadvice',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Userhelp/addadvice',
		remark : '添加意见反馈',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	PDRECHARGEDENOMINATIONLIST : {
		domain : ROOT_URL,
		apiUrl : 'Pdrecharge/pdrechargeDenominationList',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Pdrecharge/pdrechargeDenominationList',
		remark : '预存款充值面额列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	PDRECHARGERECHARGEADD : {
		domain : ROOT_URL,
		apiUrl : 'Pdrecharge/rechargeAdd',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Pdrecharge/rechargeAdd',
		remark : '充值添加',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	PDRECHARGEPDLOGLIST : {
		domain : ROOT_URL,
		apiUrl : 'Pdrecharge/pdLogList',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Pdrecharge/pdLogList',
		remark : '余额明细',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	USERMIXEDSTATENUM : {
		domain : ROOT_URL,
		apiUrl : 'User/mixedStateNum',
		author : '韩文博',
		fetchUrl : ROOT_URL+'User/mixedStateNum',
		remark : '个人中心混合的各种状态数量',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	MESSAGEUNREADGROUPCOUNT : {
		domain : ROOT_URL,
		apiUrl : 'Message/unreadGroupCount',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Message/unreadGroupCount',
		remark : '未读消息分组数量',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	MESSAGEINFODETAILMESSAGELIST : {
		domain : ROOT_URL,
		apiUrl : 'Message/infoDetailMessageList',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Message/infoDetailMessageList',
		remark : '广告通知列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	MESSAGEORDERSENDMESSAGELIST : {
		domain : ROOT_URL,
		apiUrl : 'Message/orderSendMessageList',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Message/orderSendMessageList',
		remark : '发货通知列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	MESSAGEVOUCHERSENDMESSAGELIST : {
		domain : ROOT_URL,
		apiUrl : 'Message/voucherSendMessageList',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Message/voucherSendMessageList',
		remark : '优惠券通知列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	SETTINGBASIC : {
		domain : ROOT_URL,
		apiUrl : 'Setting/basic',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Setting/basic',
		remark : '基础的配置',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	USERPHONEUNBINDOPENUSER : {
		domain : ROOT_URL,
		apiUrl : 'User/phoneUnbindOpenUser',
		author : '韩文博',
		fetchUrl : ROOT_URL+'User/phoneUnbindOpenUser',
		remark : '手机解绑微信',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	USEROPENUSERUNBINDPHONE : {
		domain : ROOT_URL,
		apiUrl : 'User/openUserUnbindPhone',
		author : '韩文博',
		fetchUrl : ROOT_URL+'User/openUserUnbindPhone',
		remark : '解绑手机',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	ADDRESSCUSTOMAREASTREET:{
		domain : ROOT_URL,
		apiUrl : 'address/customAreaStreet',
		author : '韩文博',
		fetchUrl : ROOT_URL+'address/customAreaStreet',
		remark : '曹鲜生特殊定制全部城市数据接口',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	GOODSCOUDANCONDITION:{
		domain : ROOT_URL,
		apiUrl : 'Goods/couDanCondition',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Goods/couDanCondition',
		remark : '凑单条件',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	GOODSCOUDAN:{
		domain : ROOT_URL,
		apiUrl : 'Goods/couDan',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Goods/couDan',
		remark : '凑单列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	ORDERREFUNDREFUNDREASONLIST:{
		domain : ROOT_URL,
		apiUrl : 'Orderrefund/refundReasonList',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Orderrefund/refundReasonList',
		remark : '退款原因',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : false,
		showLoading : false,
	},
	ORDERREFUNDADDREFUNDALL:{
		domain : ROOT_URL,
		apiUrl : 'Orderrefund/addRefundAll',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Orderrefund/addRefundAll',
		remark : '提交全部退款',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	USERISALLOWADDINVITER:{
		domain : ROOT_URL,
		apiUrl : 'User/isAllowAddInviter',
		author : '韩文博',
		fetchUrl : ROOT_URL+'User/isAllowAddInviter',
		remark : '是否允许添加邀请人',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	MESSAGEUNREADALLCOUNT:{
		domain : ROOT_URL,
		apiUrl : 'Message/unreadAllCount',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Message/unreadAllCount',
		remark : '全部未读消息',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	CARDBUYLIST:{
		domain : ROOT_URL,
		apiUrl : 'Card/cardBuyList',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Card/cardBuyList',
		remark : '用户购买的卡券列表',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	CARDBUYDETAIL:{
		domain : ROOT_URL,
		apiUrl : 'Card/cardBuyDetail',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Card/cardBuyDetail',
		remark : '用户购买的卡券的详情',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	CARDACTIVATEORDERDETAIL:{
		domain : ROOT_URL,
		apiUrl : 'Cardactivateorder/detail',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Cardactivateorder/detail',
		remark : '卡券激活订单详情',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	CARDACTIVATE:{
		domain : ROOT_URL,
		apiUrl : 'Card/cardActivate',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Card/cardActivate',
		remark : '卡券激活',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	ACTUALCARDACTIVATE:{
		domain : ROOT_URL,
		apiUrl : 'Card/actualCardActivate',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Card/actualCardActivate',
		remark : '实物卡激活',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	CARDCARDURLANALYSIS:{
		domain : ROOT_URL,
		apiUrl : 'card/cardUrlAnalysis',
		author : '孙泉',
		fetchUrl : ROOT_URL+'card/cardUrlAnalysis',
		remark : '微信创建卡券时自定义链接解析',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	USERWECHATOAUTH : {
		domain : ROOT_URL,
		apiUrl : 'User/wechatOauth',
		author : '韩文博',
		fetchUrl : ROOT_URL+'User/wechatOauth',
		remark : '微信授权登陆',
		method : 'GET',
		tableName : 'ez_store',
		showLoading : true,
	},
	GETWECHATJSSDK : {
		domain : ROOT_URL,
		apiUrl : 'Wechat/getJSSDKSignPackage',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Wechat/getJSSDKSignPackage',
		remark : '获得JSSDK的配置',
		method : 'POST',
		tableName : 'ez_store',
		showLoading : false,
	},
	CONFIGLISTS : {
		domain : ROOT_URL,
		apiUrl : 'Config/lists',
		author : '韩文博',
		fetchUrl : ROOT_URL+'Config/lists',
		remark : 'APP基础信息',
		method : 'GET',
		tableName : 'ez_store',
		showLoading : false,
	},
	USERTESTUSER : {
		domain : ROOT_URL,
		apiUrl : 'user/testUser',
		author : '韩文博',
		fetchUrl : ROOT_URL+'user/testUser',
		remark : 'APP基础信息',
		method : 'GET',
		tableName : 'ez_store',
		showLoading : true,
	},
	CARDGIFTPACKS : {
		domain : ROOT_URL,
		apiUrl : 'Card/giftPacks',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Card/giftPacks',
		remark : '大礼包',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : false,
	},
	CARDACTIVATEORDERLOGDETAIL : {
		domain : ROOT_URL,
		apiUrl : 'Cardactivateorder/logDetail',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Cardactivateorder/logDetail',
		remark : '申请换货的发货数据详情',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	CARDACTIVATEORDERAPPLYEXCHANGEADD : {
		domain : ROOT_URL,
		apiUrl : 'Cardactivateorder/applyExchangeAdd',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Cardactivateorder/applyExchangeAdd',
		remark : '申请换货添加',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	CARDACTIVATEORDEREXCHANGEINFO : {
		domain : ROOT_URL,
		apiUrl : 'Cardactivateorder/exchangeInfo',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Cardactivateorder/exchangeInfo',
		remark : '申请换货的换货订单数据详情',
		method : 'GET',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	CARDACTIVATEORDEREXCHANGESHIPPINGCODEADD : {
		domain : ROOT_URL,
		apiUrl : 'Cardactivateorder/exchangeShippingCodeAdd',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Cardactivateorder/exchangeShippingCodeAdd',
		remark : '添加换货快递单号',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	CARDACTIVATEORDEREXCHANGERECEIVE : {
		domain : ROOT_URL,
		apiUrl : 'Cardactivateorder/exchangeReceive',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Cardactivateorder/exchangeReceive',
		remark : '换货订单收货',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	CARDACTIVATEORDERRECEIVE : {
		domain : ROOT_URL,
		apiUrl : 'Cardactivateorder/receive',
		author : '孙泉',
		fetchUrl : ROOT_URL+'Cardactivateorder/receive',
		remark : '订单记录（配送进度）收货',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	USERSENDSETPAYPASSSMS : {
		domain : ROOT_URL,
		apiUrl : 'User/sendSetPayPassSms',
		author : '孙泉',
		fetchUrl : ROOT_URL+'User/sendSetPayPassSms',
		remark : '发送设置支付密码校正码',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	USERSETPAYPASS : {
		domain : ROOT_URL,
		apiUrl : 'User/setPayPass',
		author : '孙泉',
		fetchUrl : ROOT_URL+'User/setPayPass',
		remark : '设置支付密码',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	USERPAYPASSEDIT : {
		domain : ROOT_URL,
		apiUrl : 'User/payPassEdit',
		author : '孙泉',
		fetchUrl : ROOT_URL+'User/payPassEdit',
		remark : '修改支付密码',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	USERSENDFINDPAYPASSSMS : {
		domain : ROOT_URL,
		apiUrl : 'User/sendFindPayPassSms',
		author : '孙泉',
		fetchUrl : ROOT_URL+'User/sendFindPayPassSms',
		remark : '发送找回支付密码校正码',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},
	USERFINDPAYPASS : {
		domain : ROOT_URL,
		apiUrl : 'User/findPayPass',
		author : '孙泉',
		fetchUrl : ROOT_URL+'User/findPayPass',
		remark : '找回支付密码',
		method : 'POST',
		tableName : 'ez_store',
		needLogin : true,
		showLoading : true,
	},

}
